export const SET_PROVIDER_DATA = 'SET_PROVIDER_DATA';
export const SET_ASTRO_DATA = 'SET_ASTRO_DATA';
export const SET_DASHBOARD = 'SET_DASHBOARD';
export const SET_FIREBASE_ID = 'SET_FIREBASE_ID';
export const IS_LOADING = 'IS_LOADING';

