export const SET_PROVIDER_DATA = 'SET_PROVIDER_DATA';
export const SET_DASHBOARD = 'SET_DASHBOARD';
export const SET_FIREBASE_ID = 'SET_FIREBASE_ID';
export const SET_CHAT_REQUEST = 'SET_CHAT_REQUEST';
export const CLEAN_STORE = 'CLEAN_STORE';
export const IS_LOADING = 'IS_LOADING';
export const SET_LIVE_CLASS_COMMENTS = 'SET_LIVE_CLASS_COMMENTS';
export const SET_ASTRO_FIREBASE_ID = 'SET_ASTRO_FIREBASE_ID'
export const SET_CUSTOMER_FIREBASE_ID = 'SET_CUSTOMER_FIREBASE_ID'
export const SET_SCREEN_TYPE = 'SET_SCREEN_TYPE'
export const SET_CHAT_REQUEST_DATA = 'SET_CHAT_REQUEST_DATA'
export const SET_IS_ACTIVE_DEVICE = 'SET_IS_ACTIVE_DEVICE'

